/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const delete_record: (a: number, b: number, c: number, d: number) => any;
export const get_record: (a: number, b: number, c: number, d: number) => any;
export const list_records: (a: number, b: number) => any;
export const open: (a: number, b: number) => any;
export const put_record: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const start: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd5db4addbd66c50a: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h32ca3517c0856aa3: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3083644178357d32: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h19a1235879b3830c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h22cf045be9df4569: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1897a61d1a5b3e1d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h064b383873395853: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__ha18f15979365619b: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
